/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-fuerte-common-tutorials-0.2.3/debian/ros-fuerte-common-tutorials/opt/ros/fuerte/stacks/common_tutorials/actionlib_tutorials/msg/CarryarmFeedback.msg */
#ifndef ACTIONLIB_TUTORIALS_MESSAGE_CARRYARMFEEDBACK_H
#define ACTIONLIB_TUTORIALS_MESSAGE_CARRYARMFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct CarryarmFeedback_ {
  typedef CarryarmFeedback_<ContainerAllocator> Type;

  CarryarmFeedback_()
  : sequence()
  {
  }

  CarryarmFeedback_(const ContainerAllocator& _alloc)
  : sequence(_alloc)
  {
  }

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _sequence_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  sequence;


  typedef boost::shared_ptr< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CarryarmFeedback
typedef  ::actionlib_tutorials::CarryarmFeedback_<std::allocator<void> > CarryarmFeedback;

typedef boost::shared_ptr< ::actionlib_tutorials::CarryarmFeedback> CarryarmFeedbackPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::CarryarmFeedback const> CarryarmFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b81e37d2a31925a0e8ae261a8699cb79";
  }

  static const char* value(const  ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb81e37d2a31925a0ULL;
  static const uint64_t static_value2 = 0xe8ae261a8699cb79ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "actionlib_tutorials/CarryarmFeedback";
  }

  static const char* value(const  ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32[] sequence \n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sequence);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CarryarmFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::actionlib_tutorials::CarryarmFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_CARRYARMFEEDBACK_H

