#!/bin/sh

rosbag record \
   /area_markers \
   /attached_objects \
   /attached_objects_array \
   /blackboard/areas \
   /blackboard/beginEpisode \
   /blackboard/dispatched_action_info \
   /blackboard/endEpisode \
   /blackboard/floor_areas \
   /blackboard/fluent_name_translation \
   /blackboard/instructorAchieve \
   /blackboard/instructor_abort \
   /blackboard/instructor_teach \
   /blackboard/intent \
   /blackboard/monitored_failure \
   /blackboard/new_fluents \
   /blackboard/passiveObjectTopic \
   /blackboard/plan \
   /blackboard/sparql_init_knowledge \
   /blackboard/stefan_activity_all \
   /blackboard/stefan_arm_on \
   /blackboard/stefan_dispatcher_move \
   /blackboard/stefan_dispatcher_move_activity \
   /blackboard/stefan_dispatcher_trace \
   /blackboard/stefan_failure \
   /blackboard/stefan_grasp \
   /blackboard/stefan_result \
   /blackboard/stefan_start \
   /blackboard/stefan_trace \
   /blackboard/timeline_activity_all \
   /blackboard/timeline_all_fluents \
   /blackboard/timeline_dispatcher_arm_posture \
   /blackboard/timeline_dispatcher_arm_posture_all \
   /blackboard/timeline_dispatcher_holding \
   /blackboard/timeline_dispatcher_holding_all \
   /blackboard/timeline_dispatcher_mug \
   /blackboard/timeline_dispatcher_mug_all \
   /blackboard/timeline_dispatcher_on \
   /blackboard/timeline_dispatcher_on_all \
   /blackboard/timeline_dispatcher_robot_at \
   /blackboard/timeline_dispatcher_robot_at_all \
   /blackboard/timeline_dispatcher_torso_posture \
   /blackboard/timeline_dispatcher_torso_posture_all \
   /blackboard/timeline_has_bounded_upper_StartTime \
   /blackboard/timeline_has_upper_PhysicalEntity \
   /blackboard/timeline_is_race_TorsoPosture \
   /blackboard/timeline_is_race_leftArm1_or_has_race_ArmPosture \
   /blackboard/timeline_is_race_rightArm1_or_has_race_ArmPosture \
   /blackboard/timeline_is_upper_At \
   /blackboard/timeline_is_upper_ElementaryRobotActivity \
   /blackboard/timeline_is_upper_Experience \
   /blackboard/timeline_is_upper_InstructorDialogMove \
   /blackboard/timeline_is_upper_On \
   /blackboard/timeline_is_upper_RobotActivity \
   /blackboard/timeline_is_upper_RobotAt \
   /blackboard/timeline_is_upper_RobotPosture \
   /blackboard/timeline_semantic_dispatcher \
   /blackboard/updated_fluents \
   /base_scan_throttled \
   /display_joint_goal \
   /display_path \
   /gazebo/model_states \
   /generated_shop2_plan \
   /grasp_markers \
   /interpolation_markers \
   /map \
   /move_base_node/DWAPlannerROS/global_plan \
   /move_base_node/DWAPlannerROS/local_plan \
   /move_base_node/NavfnROS/plan \
   /move_base_node/current_goal \
   /move_base_node/local_costmap/inflated_obstacles \
   /move_base_node/local_costmap/obstacles \
   /move_base_node/local_costmap/robot_footprint \
   /move_left_arm_markers \
   /move_right_arm_markers \
   /object_manipulator/grasp_execution_markers \
   /particlecloud \
   /perception/scene_manager/object_detection_array \
   /planning_scene_markers \
   /point_cluster_grasp_planner_markers \
   /tabletop_objects \
   /tabletop_object_recognition_markers \
   /tabletop_segmentation_markers \
   /tf \
   /visualization_marker \
   /head_mount_kinect/rgb/image_raw \
   /head_mount_kinect/rgb/camera_info \
   /head_mount_kinect/depth_registered/image_raw \
   /head_mount_kinect/depth_registered/camera_info \
   /r_gripper_controller/state \
   /r_gripper_controller/command \
   /l_gripper_controller/state \
   /l_gripper_controller/command \
   /object_search_marker \
   /next_best_view_marker
